### PR TITLE
Fix: local eligibility server

### LINKED ISSUE #880: Local Eligibility Server fails to start
The local Eligibility Server fails to start both when starting with the devcontainer, and from the command line:

```bash
docker compose up server
```

Part of this will be fixed when cal-itp/eligibility-server#137 is resolved.

We also need to update the [devcontainer configuration for the server](https://github.com/cal-itp/benefits/tree/dev/.devcontainer/server) to take advantage of the new settings configuration introduced in cal-itp/eligibility-server#119

Note that the published Docker image _does not contain_ the sample configuration, keys, or data -- so this must be loaded/available via Benefits for local testing.

This will be slightly easier once cal-itp/eligibility-server#136 is merged, as we can just point to the sample keys in the Server repo.

### PR DESCRIPTION
**Pull request by thekaveman**
Closes #880.

Update to use the new settings format. 

The local eligibility server now works within the devcontainer and locally with:

```bash
docker compose up server
```

Added a line to the `bin/build.sh` helper script to pull the latest `server` image from GHCR.

## Testing

The following should give a verification success:

1. Set `DJANGO_LOAD_SAMPLE_DATA=true`, remove any custom sample data migrations
2. Open the devcontainer with this branch
3. F5 to run the Benefits app
4. Configuration: `ABC` with `Courtesy Cards`
5. User: `B2345678, Hernandez`

Notice output in the `server` Docker logs:

```console
+ bin/init.sh
+ python setup.py
+ nginx
+ python -m gunicorn -c /home/calitp/run/gunicorn.conf.py eligibility_server.app:app
[2022-09-01 23:56:09 +0000] [11] [INFO] Starting gunicorn 20.1.0
[2022-09-01 23:56:09 +0000] [11] [INFO] Listening at: unix:/home/calitp/run/gunicorn.sock (11)
[2022-09-01 23:56:09 +0000] [11] [INFO] Using worker: sync
[2022-09-01 23:56:09 +0000] [14] [INFO] Booting worker with pid: 14
[2022-09-01 23:56:09 +0000] [15] [INFO] Booting worker with pid: 15
[2022-09-01 23:56:09 +0000] [16] [INFO] Booting worker with pid: 16
[2022-09-01 23:56:09 +0000] [17] [INFO] Booting worker with pid: 17
[2022-09-01 23:56:09 +0000] [18] [INFO] Booting worker with pid: 18
[01/Sep/2022:23:58:27 +0000] "GET /verify HTTP/1.1" 200 1210 "-" "python-requests/2.28.1" "-"
 - - [01/Sep/2022:23:58:27 +0000] "GET /verify HTTP/1.0" 200 1210 "-" "python-requests/2.28.1"
```

### CODE REVIEW

File: bin/build.sh [hunk 1]
```diff
@@ -4,3 +4,5 @@ set -eux
 docker compose build client
 
 docker compose build dev
+
+docker compose pull server
```
Comment (angela-tran) [inline bin/build.sh:8]: 💯

**Review by angela-tran — APPROVED** [review]

**Comment by angela-tran** [comment]
I was able to run all this locally
